---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello 
  name: hello 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello 
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - image: tektutor-spring-microservice:latest 
        name: hello 

        env:
        - name: USERNAME 
          valueFrom: 
            secretKeyRef:
              name: mariadb-login-credentials
              key: username

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-login-credentials
              key: password

        - name: JDBC_URL 
          valueFrom:
            configMapKeyRef:
              name: mariadb-configuration 
              key: jdbc_url 

        volumeMounts:
        - name: mariadb-storage
          mountPath: /bitnami/mariadb/data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello 
  name: hello 
spec:
  ports:
  - port: 8080 
    protocol: TCP
    targetPort: 8080 
  selector:
    app: hello 
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello 
  name: hello 
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: hello 
    weight: null
---
